apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-healer-deployment
  labels:
    app: auto-healer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auto-healer
  template:
    metadata:
      labels:
        app: auto-healer
    spec:
      serviceAccountName: aiops-sa
      containers:
      - name: auto-healer
        image: dakshsawhneyy/aiops-auto-healer:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "200m"  
            memory: "256Mi" 
          limits:
            cpu: "500m"  
            memory: "512Mi"